export const LOGIN_WITH_OAUTH_LOADING = 'LOGIN_WITH_OAUTH_LOADING';
export const LOGIN_WITH_OAUTH_SUCCESS = 'LOGIN_WITH_OAUTH_SUCCESS';
export const LOGIN_WITH_OAUTH_FAIL = 'LOGIN_WITH_OAUTH_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_WITH_EMAIL_LOADING = 'LOGIN_WITH_EMAIL_LOADING';
export const LOGIN_WITH_EMAIL_SUCCESS = 'LOGIN_WITH_EMAIL_SUCCESS';
export const LOGIN_WITH_EMAIL_FAIL = 'LOGIN_WITH_EMAIL_FAIL';

export const REGISTER_WITH_EMAIL_LOADING = 'REGISTER_WITH_EMAIL_LOADING';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAIL = 'REGISTER_WITH_EMAIL_FAIL';

export const ME_LOADING = 'ME_LOADING';
export const ME_SUCCESS = 'ME_SUCCESS';
export const ME_FAIL = 'ME_FAIL';


export const GET_SHOP_LOADING = 'GET_SHOP_LOADING';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAIL = 'GET_SHOP_FAIL';

export const GET_NEARBY_LOADING = 'GET_NEARBY_LOADING';
export const GET_NEARBY_SUCCESS = 'GET_NEARBY_SUCCESS';
export const GET_NEARBY_FAIL = 'GET_NEARBY_FAIL';

export const GET_BARBER_LOADING = 'GET_BARBER_LOADING';
export const GET_BARBER_SUCCESS = 'GET_BARBER_SUCCESS';
export const GET_BARBER_FAIL = 'GET_BARBER_FAIL';

export const GET_SERVICES_LOADING = 'GET_SERVICES_LOADING';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAIL = 'GET_SERVICES_FAIL';

export const GET_TIMES_LOADING = 'GET_TIMES_LOADING';
export const GET_TIMES_SUCCESS = 'GET_TIMES_SUCCESS';
export const GET_TIMES_FAIL = 'GET_TIMES_FAIL';

export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ADD_CART = 'ADD_CART' ;
export const DELETE_CART = 'DELETE_CART';

export const SEND_PAYMENT_LOADING = 'SEND_PAYMENT_LOADING';
export const SEND_PAYMENT_SUCCESS = 'SEND_PAYMENT_SUCCESS';
export const SEND_PAYMENT_FAIL = 'SEND_PAYMENT_FAIL';

export const ADD_BOOKING_LOADING = 'ADD_BOOKING_LOADING';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL';